services:
  mqtt-broker:
    image: rabbitmq:4.1-rc-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=deppcamera
      - RABBITMQ_DEFAULT_PASS=deepcamera_guest
    ports:
      - 5672:5672
      - 15672:15672
  mongo:
    image: mongo:noble
    ports:
        - 27017:27017
    logging:
        options:
            max-size: 1g
    environment:
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=bdung
    volumes:
      - ./db:/data/db

volumes:
  mongodb_data:
